# Generated by Django 2.1.4 on 2019-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=56)),
                ('pages', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
